name: Bearer

on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Bearer
        uses: bearer/bearer-action@828eeb928ce2f4a7ca5ed57fb8b59508cb8c79bc # v2
        with:
          format: sarif
          output: results.sarif